services:
    run:
        deploy:
            restart_policy:
                condition: none
            # 시스템 상황에 따라 조정할 것
            replicas: 8
        environment:
            # docker swarm에서 gpu 사용을 위한 환경 변수 
            - NVIDIA_VISIBLE_DEVICES=ALL
            - python_args=--my_ai rl --opponent random --episode=100 --map=all --gui false --repeat 0 --diff-strategy
        image: competition
