services:
    competition:
        deploy:
            replicas: 5
            resources:
                reservations:
                    #gpu 사용
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        environment:
            - python_args=--my_ai rl --opponent random --episode=100 --map=all --gui false --repeat 0 --strategy default
        image: competition
